version: '3.1'

services:
  springapp:
    image: 488761648037.dkr.ecr.ap-south-1.amazonaws.com/spring_boot:1
    environment:
    - MONGO_DB_HOSTNAME=mongodb
    - MONGO_DB_USERNAME=mongo
    - MONGO_DB_PASSWORD=mongo123
    ports:
    - 8080:8080
    networks:
    - swramnetwork
    depends_on:
    - mongodb
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5


  mongodb:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongo
    - MONGO_INITDB_ROOT_PASSWORD=mongo123
    volumes:
      - mongodbebs:/dev/config
    networks:
    - swramnetwork

volumes:
  mongodbebs:
    external: true

networks:
  swramnetwork:
    driver: overlay
    external: true
